import { Avatar, Tooltip } from "flowbite-react";
import Head from "next/head";

export default function Cases() {
    return (
        <>
            <Head>
                <title>Record Warden - Case #001</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-col p-5">
                <div className="flex flex-row justify-between">
                    <div className="text-3xl text-white">Case #001</div>
                    <div className="text-xl text-white flex flex-row items-center justify-center h-full bg-gray-700 py-1 px-3 rounded-lg">Case Status: &nbsp;<span className="text-green-400 text-2xl">&nbsp;Open</span></div>
                </div>
                <div className="text-md text-gray-500 mt-3">Ani stole 69420$ from indian bank and then he decided to go to sudhan home and share him some money but then he also bringed some russians for the fun but soon as they started to watch some anime for fun, they heard a knock at the door which is the police inquiring about the russian girls in their house and they decided to share it with the police, showing how corrupted our system is . If police start getting sold for russians, what is the future of our country? This case is registered not on Ani or Sudhan but on the Police who got sold so easily and the government officials who hired these corrupted individuals.</div>
            </div>

            <div className="flex flex-row w-screen">
                <div className="items-center flex flex-col w-1/3">
                    <div className="mt-5 text-2xl text-white text-center">Case Information</div>
                    <div className="flex flex-col w-full p-5">
                        <div className="flex flex-row text-gray-300 text-xl">
                            Lawyers:
                            <Tooltip content="Nahida">
                                <Avatar className="ml-3" img="https://cdn.discordapp.com/attachments/1106611314891161663/1156610031836483674/nahida.jpg"/>
                            </Tooltip>
                        </div>
                    </div>
                </div>
                <div className="items-center justify-center flex flex-col w-2/3">
                    <div className="mt-5 text-2xl text-white text-center">Case History</div>
                    <div className="mt-5 flex flex-col w-full overflow-y-scroll hideScroll">
                        <ol className="m-5 p-5 relative border-l border-gray-200 dark:border-gray-700">
                            <li className="mb-10 ml-6">
                                <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -left-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                                    <img className="rounded-full shadow-lg" src="https://media.discordapp.net/attachments/1106611314891161663/1156604265540882492/3.jpg?ex=65159329&is=651441a9&hm=49ae12bed4e03a007c644ac96672e6c18b8930b47f5945db5e37f619fcc8cf11&=" />
                                </span>
                                <div className="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                                    <time className="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0">just now</time>
                                    <div className="text-sm font-normal text-gray-500 dark:text-gray-300">Venti changed <a href="#" className="font-semibold text-blue-600 dark:text-blue-500 hover:underline">Case #001</a> description to <span className="bg-gray-100 text-gray-800 text-xs font-normal mr-2 px-2.5 py-0.5 rounded dark:bg-gray-600 dark:text-gray-300">Ani stole 69420$...</span></div>
                                </div>
                            </li>
                            <li className="mb-10 ml-6">
                                <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -left-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                                    <img className="rounded-full shadow-lg" src="https://media.discordapp.net/attachments/1106611314891161663/1156604265540882492/3.jpg?ex=65159329&is=651441a9&hm=49ae12bed4e03a007c644ac96672e6c18b8930b47f5945db5e37f619fcc8cf11&=" />
                                </span>
                                <div className="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                                    <time className="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0">2 hours ago</time>
                                    <div className="text-sm font-normal text-gray-500 dark:text-gray-300">Venti added <a href="#" className="font-semibold text-blue-600 dark:text-blue-500 hover:underline">Sudhan</a> as a  <span className="bg-gray-100 text-gray-800 text-xs font-normal mr-2 px-2.5 py-0.5 rounded dark:bg-gray-600 dark:text-gray-300">Lawyer</span>to this case</div>
                                </div>
                            </li>
                            <li className="mb-10 ml-6">
                                <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -left-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                                    <img className="rounded-full shadow-lg" src="https://media.discordapp.net/attachments/1106611314891161663/1156604265540882492/3.jpg?ex=65159329&is=651441a9&hm=49ae12bed4e03a007c644ac96672e6c18b8930b47f5945db5e37f619fcc8cf11&=" />
                                </span>
                                <div className="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                                    <time className="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0">2 hours ago</time>
                                    <div className="text-sm font-normal text-gray-500 dark:text-gray-300">Venti added <a href="#" className="font-semibold text-blue-600 dark:text-blue-500 hover:underline">Sudhan</a> as a  <span className="bg-gray-100 text-gray-800 text-xs font-normal mr-2 px-2.5 py-0.5 rounded dark:bg-gray-600 dark:text-gray-300">Lawyer</span>to this case</div>
                                </div>
                            </li>
                            <li className="mb-10 ml-6">
                                <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -left-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                                    <img className="rounded-full shadow-lg" src="https://media.discordapp.net/attachments/1106611314891161663/1156604265540882492/3.jpg?ex=65159329&is=651441a9&hm=49ae12bed4e03a007c644ac96672e6c18b8930b47f5945db5e37f619fcc8cf11&=" />
                                </span>
                                <div className="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                                    <time className="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0">2 hours ago</time>
                                    <div className="text-sm font-normal text-gray-500 dark:text-gray-300">Venti added <a href="#" className="font-semibold text-blue-600 dark:text-blue-500 hover:underline">Sudhan</a> as a  <span className="bg-gray-100 text-gray-800 text-xs font-normal mr-2 px-2.5 py-0.5 rounded dark:bg-gray-600 dark:text-gray-300">Lawyer</span>to this case</div>
                                </div>
                            </li>
                            <li className="ml-6">
                                <span className="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -left-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
                                    <img className="rounded-full shadow-lg" src="https://media.discordapp.net/attachments/1106611314891161663/1156604265540882492/3.jpg?ex=65159329&is=651441a9&hm=49ae12bed4e03a007c644ac96672e6c18b8930b47f5945db5e37f619fcc8cf11&=" />
                                </span>
                                <div className="items-center justify-between p-4 bg-white border border-gray-200 rounded-lg shadow-sm sm:flex dark:bg-gray-700 dark:border-gray-600">
                                    <time className="mb-1 text-xs font-normal text-gray-400 sm:order-last sm:mb-0">1 day ago</time>
                                    <div className="text-sm font-normal text-gray-500 lex dark:text-gray-300">Venti has added a <a href="#" className="font-semibold text-blue-600 dark:text-blue-500 hover:underline">Document (Russian Girls.png)</a> to  <span className="font-semibold text-gray-900 dark:text-white">Case #001</span></div>
                                </div>
                            </li>

                        </ol>
                    </div>
                </div>
            </div>
        </>
    );
}
