import { Button, Select, TextInput } from "flowbite-react";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Record Warden - Admin</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="text-3xl text-white text-center">Grant Role to Users</div>
            <div className="mt-5 flex flex-row w-full justify-center items-center">
                <TextInput className="px-3" placeholder="0x..." />
                <Select className="px-3" id="role">
                    <option selected>Choose a role</option>
                    <option>Judge</option>
                    <option>Lawyer</option>
                </Select>
                <Button className="px-3">Grant Role</Button>
            </div>
        </>
    );
}
