import Head from "next/head";

export default function Cases() {
  return (
    <>
      <Head>
        <title>Record Warden - Cases</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl text-white text-center">Cases</div>
    </>
  );
}
