import Head from "next/head";

export default function Cases() {
  return (
    <>
      <Head>
        <title>Record Warden - Documents</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
