import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Record Warden</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-3xl text-white text-center">Landing page coming soon!!!</div>
    </>
  );
}
