import Head from "next/head";
import Link from "next/link";

export default function Cases() {
    return (
        <>
            <Head>
                <title>Record Warden - Cases</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="px-5 flex flex-col">
                <div className="text-3xl text-white">Your Cases</div>
                <div className="mt-5 relative overflow-x-auto shadow-md sm:rounded-lg">
                    <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" className="px-6 py-3">
                                    Case ID
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Description
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Lawyers
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Created At
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0001
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Ani&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>, Sudhan&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>
                                </td>
                                <td className="px-6 py-4">
                                    {new Date(1279267555432).toLocaleString()}
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                            <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0002
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Ani&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>, Sudhan&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>
                                </td>
                                <td className="px-6 py-4">
                                    {new Date(1279267555432).toLocaleString()}
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0004
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Ani&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>, Sudhan&nbsp;<span className="text-gray-400">{"("}0x847328472343{")"}</span>
                                </td>
                                <td className="px-6 py-4">
                                    {new Date(1279267555432).toLocaleString()}
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </>
    );
}
