import { Avatar } from "flowbite-react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Record Warden - Nahida</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="px-5 flex flex-col">
                <div className="mt-10 py-5 px-7 flex flex-row justify-between relative">
                    <Avatar rounded size="lg" className="absolute -translate-y-11 scale-125 hover:scale-150" img="https://cdn.discordapp.com/attachments/1106611314891161663/1156610031836483674/nahida.jpg" />
                    <div className="flex flex-col h-full w-auto pl-28 -translate-y-4">
                        <div className="text-2xl text-white select-text">Nahida</div>
                        <div className="text-lg text-gray-500 select-text">nahida_pro</div>
                    </div>
                    <div className="flex flex-col items-center justify-center -translate-y-4">
                        <div className="border-2 border-blue-400 hover:bg-blue-500 hover:text-white hover:scale-105 text-gray-300 rounded-lg px-5 py-2 cursor-pointer">Message</div>
                    </div>
                </div>

                <div className="flex flex-row justify-between w-auto h-auto">
                    <div className="bg-gray-800 h-auto w-7/12 rounded-lg p-3">
                        <div className="flex flex-col">
                            <div className="text-md text-white font-semibold select-text">About me</div>
                            <div className="text-md text-gray-400 mt-1 leading-5 select-text">I am the dendro archon the real one the destroyer of sudhan</div>
                        </div>
                    </div>
                    <div className="bg-gray-800 h-auto w-4/12 rounded-lg p-3">
                        <div className="flex flex-col">
                            <div className="text-md text-white font-semibold select-text">Location</div>
                            <div className="text-md text-gray-400 mt-1 leading-5 select-text">Sumeru, Teyvat</div>
                        </div>
                        <div className="flex flex-col mt-5">
                            <div className="text-md text-white font-semibold select-text">Email</div>
                            <div className="text-md text-gray-400 mt-1 leading-5 select-text">nahida@genshin.impact</div>
                        </div>
                    </div>
                </div>

                <div className="text-3xl text-white font-semibold mt-8">Past cases</div>

                <div className="mt-5 relative overflow-x-auto shadow-md sm:rounded-lg">
                    <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" className="px-6 py-3">
                                    Case ID
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Description
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Status
                                </th>
                                <th scope="col" className="px-6 py-3">
                                    Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0001
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Open
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                            <tr className="border-b bg-gray-50 dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0002
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Open
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                            <tr className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 text-gray-200">
                                <th scope="row" className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white text-lg">
                                    #0004
                                </th>
                                <td className="px-6 py-4">
                                    Robbery
                                </td>
                                <td className="px-6 py-4">
                                    Closed
                                </td>
                                <td className="px-6 py-4">
                                    <Link href="/cases/001" className="font-medium text-blue-600 dark:text-blue-500 hover:underline">View Full Details</Link>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </>
    );
}
