import { Button, Select, TextInput } from "flowbite-react";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Record Warden - Nahida</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="mx-5 flex flex-col">
                <div className="text-3xl text-white">Nahida</div>
                <div className="flex flex-row relative mt-28 h-[50vh] w-auto">
                    
                </div>
            </div>
        </>
    );
}
